name: local-infra

networks:
  local-network:
    driver: bridge

services:
  # mysql
  mysql:
    image: mysql:latest
    container_name: local_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - "3666:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
    networks:
      local-network:
        aliases:
          - mysql
  # mongodb
  mongo:
    image: mongo:latest
    container_name: local_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - ./db/mongodb/data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    networks:
      local-network:
        aliases:
          - mongo
  # redis
  redis:
    image: redis:latest
    container_name: local_redis
    restart: always
    tty: true
    ports:
      - "63792:6379"
    networks:
      local-network:
        aliases:
          - redis
  # zipkin
  zipkin:
    restart: always
    image: openzipkin/zipkin
    container_name: local_zipkin
    ports:
      - "9411:9411"
    
  # keycloak
  keycloak:
      image: quay.io/keycloak/keycloak:26.1.4
      container_name: local_keycloak
      command: [ "start-dev" ]
      restart: always
      environment:
        KC_DB: mysql
        KC_DB_URL: jdbc:mysql://mysql:3306/keycloak
        KC_DB_USERNAME: root
        KC_DB_PASSWORD: root
        KC_BOOTSTRAP_ADMIN_USERNAME: admin
        KC_BOOTSTRAP_ADMIN_PASSWORD: admin
        KC_HEALTH_ENABLED: true
        KC_METRICS_ENABLED: true
      ports:
        - "9090:8080"
      volumes:
        - "./keycloak/realms:/opt/keycloak/data/import/"
      depends_on:
        - mysql
      networks:
        local-network:
          aliases:
            - keycloak
